name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        env:
          TMDB_API: ${{ secrets.TMDB_API }}
          ZSHOW_API: ${{ secrets.ZSHOW_API }}
          ANICHI_API: ${{ secrets.ANICHI_API }}
          KissKh: ${{ secrets.KissKh }}
          KisskhSub: ${{ secrets.KisskhSub }}
          SUPERSTREAM_THIRD_API: ${{ secrets.SUPERSTREAM_THIRD_API }}
          SUPERSTREAM_FOURTH_API: ${{ secrets.SUPERSTREAM_FOURTH_API }}
          SUPERSTREAM_FIRST_API: ${{ secrets.SUPERSTREAM_FIRST_API }}
          PROXYAPI: ${{ secrets.PROXYAPI }}
          KAISVA: ${{ secrets.KAISVA }}
          MOVIEBOX_SECRET_KEY_ALT: ${{ secrets.MOVIEBOX_SECRET_KEY_ALT }}
          MOVIEBOX_SECRET_KEY_DEFAULT: ${{ secrets.MOVIEBOX_SECRET_KEY_DEFAULT }}
          KAIMEG: ${{ secrets.KAIMEG }}
          KAIDEC: ${{ secrets.KAIDEC }}
          KAIENC: ${{ secrets.KAIENC }}
          VideasyDEC: ${{ secrets.VideasyDEC }}
          YFXENC: ${{ secrets.YFXENC }}
          YFXDEC: ${{ secrets.YFXDEC }}
          NuvFeb: ${{ secrets.NuvFeb }}
          ANICHI_APP: ${{ secrets.ANICHI_APP }}
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson

          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/
          cp build/plugins.json $GITHUB_WORKSPACE/builds/plugins.json

          cat > $GITHUB_WORKSPACE/builds/repo.json <<'EOF'
          {
            "name": "AlaaRepo",
            "description": "إضافات من تطوير AlaaCodeLab",
            "manifestVersion": 1,
            "pluginLists": [
              "https://raw.githubusercontent.com/AlaaCodeLab/AlaaRepo/builds/plugins.json"
            ]
          }
          EOF

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
